package com.probiotics.xiaoni;

import android.app.Activity;
import android.app.AlertDialog;
import android.content.Intent;
import android.graphics.Color;
import android.net.Uri;
import android.os.Bundle;
import android.view.Gravity;
import android.view.View;
import android.view.WindowManager;
import android.widget.*;

public final class MoreActivity extends Activity {
    private static final int PICK_ROOTFS = 51;
    private int dp(int n) { return (int) (n * getResources().getDisplayMetrics().density + .5f); }
    private TextView label(String value, int size, int color) { TextView v = new TextView(this); v.setText(value); v.setTextSize(size); v.setTextColor(color); v.setGravity(Gravity.CENTER_VERTICAL); return v; }
    @Override public void onCreate(Bundle state) { super.onCreate(state); getWindow().setStatusBarColor(0xfff6f7fb); getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR); getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE); showPage(); }
    @Override protected void onResume() { super.onResume(); if (refreshWhenResumed) { refreshWhenResumed = false; int x = pageScroll == null ? 0 : pageScroll.getScrollX(); int y = pageScroll == null ? 0 : pageScroll.getScrollY(); showPage(); pageScroll.post(() -> pageScroll.scrollTo(x, y)); } }
    private boolean listReady;
    private boolean refreshWhenResumed;
    private ScrollView pageScroll;
     private void showPage() {
         LinearLayout content = new LinearLayout(this); content.setOrientation(LinearLayout.VERTICAL); content.setPadding(dp(16), dp(14), dp(16), dp(24)); content.setBackgroundColor(0xfff6f7fb); content.setOnApplyWindowInsetsListener((v, i) -> { v.setPadding(dp(16), dp(14) + i.getSystemWindowInsetTop(), dp(16), dp(24) + i.getSystemWindowInsetBottom()); return i; });
        LinearLayout header = new LinearLayout(this); header.setGravity(Gravity.CENTER_VERTICAL); header.setBackgroundResource(R.drawable.rounded_panel); Button back = new Button(this); back.setText("‹"); back.setTextSize(26); back.setAllCaps(false); back.setMinWidth(0); back.setMinHeight(0); back.setOnClickListener(v -> finish()); header.addView(back, new LinearLayout.LayoutParams(dp(48), dp(56))); TextView title = label("更多功能", 23, 0xff141d37); title.setTypeface(null, 1); header.addView(title, new LinearLayout.LayoutParams(0, dp(56), 1)); content.addView(header);
        TextView intro = label("工具箱\n扩展设备能力，独立管理 Linux 用户空间", 15, 0xff35425e); intro.setPadding(dp(6), dp(20), 0, dp(10)); content.addView(intro);
         content.addView(card(android.R.drawable.ic_menu_manage, "ARM64 Linux 终端", "在线云端下载，支持 ROOT chroot 运行", 0xff198a9b, this::openLinuxTerminalCatalog));
        content.addView(card(android.R.drawable.ic_menu_upload, "本地安装 rootfs", "选择 .tar.gz 或 .tar.xz 压缩包导入终端环境", 0xff7651b5, this::pickRootfs));
          for (LinuxImages.Image image : LinuxImages.ALL) if (LinuxImages.hasUsableShell(LinuxImages.environment(this, image))) content.addView(environmentCard(image));
         if (LinuxImages.hasUsableShell(LinuxImages.environment(this, LinuxImages.LOCAL))) content.addView(environmentCard(LinuxImages.LOCAL));
           TextView tip = label("云端镜像下载完成后，已安装环境会自动显示在这里。\n点击对应入口即可进入终端。", 13, 0xff52617b); tip.setPadding(dp(8), dp(14), dp(8), 0); content.addView(tip); ScrollView scroll = new ScrollView(this); scroll.setFillViewport(true); scroll.addView(content); pageScroll = scroll; setContentView(scroll); listReady = true;
     }
        private LinearLayout environmentCard(LinuxImages.Image image) { LinearLayout box = new LinearLayout(this); box.setOrientation(LinearLayout.VERTICAL); box.setPadding(dp(4), dp(4), dp(4), dp(4)); box.setBackgroundResource(R.drawable.rounded_panel); LinearLayout terminal = installedCard(image); terminal.setBackgroundColor(Color.TRANSPARENT); box.addView(terminal); LinearLayout storage = storageCard(image); storage.setBackgroundColor(Color.TRANSPARENT); box.addView(storage); LinearLayout packages = packageCard(image); packages.setBackgroundColor(Color.TRANSPARENT); box.addView(packages); LinearLayout.LayoutParams lp = new LinearLayout.LayoutParams(-1, -2); lp.setMargins(0, dp(8), 0, 0); box.setLayoutParams(lp); return box; }
         private LinearLayout packageCard(LinuxImages.Image image) { LinearLayout card = new LinearLayout(this); card.setGravity(Gravity.CENTER_VERTICAL); card.setPadding(dp(14), dp(6), dp(12), dp(6)); TextView count = label("正在读取用户安装包...", 12, 0xff52617b); card.addView(count, new LinearLayout.LayoutParams(0, dp(40), 1)); Button view = actionButton("查看并卸载", R.drawable.remove_pill, 0xff7651b5); view.setOnClickListener(v -> showPackages(image)); card.addView(view, new LinearLayout.LayoutParams(dp(108), dp(40))); new Thread(() -> { java.util.List<String> packages = listPackages(image); runOnUiThread(() -> count.setText(packages.isEmpty() ? "用户安装包：0 个" : "用户安装包：" + packages.size() + " 个")); }).start(); return card; }
          private java.util.List<String> listPackages(LinuxImages.Image image) { java.util.List<String> result = new java.util.ArrayList<>(); java.io.File record = new java.io.File(LinuxImages.environment(this, image), "var/lib/linux-dsu/user-packages"); try { for (String line : java.nio.file.Files.readAllLines(record.toPath(), java.nio.charset.StandardCharsets.UTF_8)) { String value = line.trim(); if (!value.isEmpty() && !result.contains(value)) result.add(value); } } catch (Exception ignored) { } return result; }
         private boolean containsLine(java.io.File file, String value) { try { for (String line : java.nio.file.Files.readAllLines(file.toPath(), java.nio.charset.StandardCharsets.UTF_8)) if (line.trim().equals(value)) return true; } catch (Exception ignored) { } return false; }
         private void showPackages(LinuxImages.Image image) { AlertDialog loading = new AlertDialog.Builder(this).setTitle(image.name + " 用户安装包").setMessage("正在读取用户安装包...").setNegativeButton("关闭", null).create(); loading.show(); new Thread(() -> { java.util.List<String> packages = listPackages(image); runOnUiThread(() -> { if (isFinishing()) return; loading.dismiss(); if (packages.isEmpty()) { new AlertDialog.Builder(this).setTitle(image.name + " 用户安装包").setMessage("没有检测到基础环境安装完成后新增的完整软件包。新下载的环境会从安装完成时建立基线。").setPositiveButton("关闭", null).show(); return; } String[] names = packages.toArray(new String[0]); new AlertDialog.Builder(this).setTitle(image.name + " 用户安装包（" + names.length + " 个）").setItems(names, (dialog, which) -> confirmUninstall(image, names[which])).setNegativeButton("关闭", null).show(); }); }).start(); }
           private void confirmUninstall(LinuxImages.Image image, String packageName) { new AlertDialog.Builder(this).setTitle("卸载用户安装包").setMessage("确定卸载完整软件包 " + packageName + " 吗？关联依赖由包管理器处理。").setNegativeButton("取消", null).setPositiveButton("卸载", (dialog, which) -> new Thread(() -> { String inner = "PKG=" + quote(packageName) + "; if [ -x /usr/bin/apt-get ]; then /usr/bin/apt-get purge -y \"$PKG\"; elif [ -x /sbin/apk ]; then /sbin/apk del \"$PKG\"; elif [ -x /usr/bin/rpm ]; then /usr/bin/rpm -e \"$PKG\"; else echo 'rootfs 中没有可用的包管理器' >&2; exit 127; fi; STATUS=$?; if [ $STATUS -eq 0 ] && [ -f /var/lib/linux-dsu/user-packages ]; then command sed -i \"/^$PKG$/d\" /var/lib/linux-dsu/user-packages; fi; exit $STATUS"; String output = runRootCommand(chrootCommand(LinuxImages.environment(this, image).getAbsolutePath(), inner)); runOnUiThread(() -> { Toast.makeText(this, output.trim().isEmpty() ? "软件包已卸载" : output.trim(), Toast.LENGTH_LONG).show(); showPage(); }); }).start()).show(); }
         private String chrootCommand(String root, String inner) { String env = "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin HOME=/root TERM=xterm-256color"; return "ROOT=" + quote(root) + "; SHELL=/bin/sh; [ -e \"$ROOT$SHELL\" ] || SHELL=/usr/bin/sh; /system/bin/toybox chroot \"$ROOT\" /usr/bin/env " + env + " \"$SHELL\" -c " + quote(inner); }
         private String runRootCommand(String command) { try { java.lang.Process process = new ProcessBuilder("/system/bin/su", "-c", command).redirectErrorStream(true).start(); StringBuilder output = new StringBuilder(); try (java.io.InputStream input = process.getInputStream()) { byte[] buffer = new byte[4096]; int count; while ((count = input.read(buffer)) != -1 && output.length() < 131072) output.append(new String(buffer, 0, count, java.nio.charset.StandardCharsets.UTF_8)); } process.waitFor(); return output.toString(); } catch (Exception e) { return ""; } }
         private String quote(String value) { return "'" + value.replace("'", "'\\''") + "'"; }
    private void pickRootfs() { Intent intent = new Intent(Intent.ACTION_OPEN_DOCUMENT); intent.addCategory(Intent.CATEGORY_OPENABLE); intent.setType("*/*"); intent.putExtra(Intent.EXTRA_MIME_TYPES, new String[]{"application/gzip", "application/x-gzip", "application/x-xz", "application/octet-stream"}); startActivityForResult(intent, PICK_ROOTFS); }
    @Override protected void onActivityResult(int requestCode, int resultCode, Intent data) { super.onActivityResult(requestCode, resultCode, data); if (requestCode == PICK_ROOTFS && resultCode == RESULT_OK && data != null && data.getData() != null) { Intent intent = new Intent(this, LinuxTerminalActivity.class); intent.putExtra("local_install", true); intent.setData(data.getData()); refreshWhenResumed = true; startActivity(intent); } }
     private void openLinuxTerminalCatalog() { refreshWhenResumed = true; startActivity(new Intent(this, LinuxTerminalActivity.class)); }
      private void openInstalled(String id) { LinuxImages.Image image = findImage(id); Intent intent = new Intent(this, LinuxTerminalActivity.class); intent.putExtra("open_image", id); intent.putExtra("open_terminal", true); if (image != null && !LinuxImages.environment(this, image).isDirectory() && LinuxImages.archive(this, image).isFile()) intent.putExtra("restore_image", true); refreshWhenResumed = true; startActivity(intent); }
     private LinuxImages.Image findImage(String id) { for (LinuxImages.Image image : LinuxImages.ALL) if (image.id().equals(id)) return image; return LinuxImages.LOCAL.id().equals(id) ? LinuxImages.LOCAL : null; }
    private LinearLayout card(int icon, String title, String subtitle, int color, Runnable click) { LinearLayout card = new LinearLayout(this); card.setGravity(Gravity.CENTER_VERTICAL); card.setPadding(dp(14), dp(10), dp(12), dp(10)); card.setBackgroundResource(R.drawable.rounded_panel); ImageView mark = new ImageView(this); mark.setImageResource(icon); mark.setColorFilter(Color.WHITE); mark.setScaleType(ImageView.ScaleType.CENTER_INSIDE); mark.setPadding(dp(8), dp(8), dp(8), dp(8)); mark.setBackgroundResource(color == 0xff7651b5 ? R.drawable.icon_tile_purple : R.drawable.icon_tile_teal); card.addView(mark, new LinearLayout.LayoutParams(dp(48), dp(48))); LinearLayout words = new LinearLayout(this); words.setOrientation(LinearLayout.VERTICAL); words.setPadding(dp(12), 0, dp(6), 0); TextView heading = label(title, 16, 0xff182b54); heading.setTypeface(null, 1); words.addView(heading, new LinearLayout.LayoutParams(-1, dp(28))); words.addView(label(subtitle, 12, 0xff5d6b84), new LinearLayout.LayoutParams(-1, dp(34))); card.addView(words, new LinearLayout.LayoutParams(0, dp(68), 1)); TextView arrow = label("›", 28, color); arrow.setGravity(Gravity.CENTER); card.addView(arrow, new LinearLayout.LayoutParams(dp(28), dp(56))); card.setOnClickListener(v -> click.run()); LinearLayout.LayoutParams lp = new LinearLayout.LayoutParams(-1, dp(90)); lp.setMargins(0, dp(8), 0, 0); card.setLayoutParams(lp); return card; }
    private LinearLayout installedCard(LinuxImages.Image image) { LinearLayout card = new LinearLayout(this); card.setOrientation(LinearLayout.VERTICAL); card.setPadding(dp(14), dp(10), dp(12), dp(10)); card.setBackgroundResource(R.drawable.rounded_panel); LinearLayout top = new LinearLayout(this); top.setGravity(Gravity.CENTER_VERTICAL); ImageView mark = new ImageView(this); mark.setImageResource(image == LinuxImages.LOCAL ? android.R.drawable.ic_menu_upload : image.name.startsWith("Ubuntu") ? android.R.drawable.ic_menu_compass : image.name.startsWith("Alpine") ? android.R.drawable.ic_menu_manage : android.R.drawable.ic_menu_view); mark.setColorFilter(Color.WHITE); mark.setPadding(dp(8), dp(8), dp(8), dp(8)); mark.setBackgroundResource(image == LinuxImages.LOCAL ? R.drawable.icon_tile_purple : R.drawable.icon_tile_green); top.addView(mark, new LinearLayout.LayoutParams(dp(48), dp(48))); LinearLayout words = new LinearLayout(this); words.setOrientation(LinearLayout.VERTICAL); words.setPadding(dp(12), 0, 0, 0); TextView heading = label(image.name, 16, 0xff182b54); heading.setTypeface(null, 1); words.addView(heading, new LinearLayout.LayoutParams(-1, dp(28))); words.addView(label("已安装 · 可直接进入终端", 12, 0xff5d6b84), new LinearLayout.LayoutParams(-1, dp(28))); top.addView(words, new LinearLayout.LayoutParams(0, dp(56), 1)); card.addView(top); LinearLayout actions = new LinearLayout(this); actions.setGravity(Gravity.CENTER_VERTICAL); actions.setPadding(dp(60), dp(8), 0, 0); Button enter = actionButton("进入终端", R.drawable.button_green, Color.WHITE); enter.setOnClickListener(v -> openInstalled(image.id())); actions.addView(enter, new LinearLayout.LayoutParams(0, dp(40), 1)); Button remove = actionButton("移除环境", R.drawable.remove_pill, 0xffc62828); remove.setOnClickListener(v -> confirmRemove(image)); LinearLayout.LayoutParams removeLp = new LinearLayout.LayoutParams(dp(104), dp(40)); removeLp.setMargins(dp(8), 0, 0, 0); actions.addView(remove, removeLp); card.addView(actions); LinearLayout.LayoutParams lp = new LinearLayout.LayoutParams(-1, dp(120)); lp.setMargins(0, dp(8), 0, 0); card.setLayoutParams(lp); return card; }
      private LinearLayout storageCard(LinuxImages.Image image) { LinearLayout card = new LinearLayout(this); card.setOrientation(LinearLayout.VERTICAL); card.setPadding(dp(14), dp(8), dp(12), dp(8)); card.setBackgroundResource(R.drawable.rounded_panel); TextView usage = label("正在计算存储占用...", 12, 0xff52617b); card.addView(usage, new LinearLayout.LayoutParams(-1, dp(28))); LinearLayout actions = new LinearLayout(this); Button clear = actionButton("清理系统数据", R.drawable.remove_pill, 0xffc62828); clear.setOnClickListener(v -> confirmClear(image, usage)); actions.addView(clear, new LinearLayout.LayoutParams(0, dp(38), 1)); Button removeArchive = actionButton("清理下载包", R.drawable.remove_pill, 0xff7651b5); removeArchive.setOnClickListener(v -> confirmClearArchive(image, usage)); LinearLayout.LayoutParams archiveLp = new LinearLayout.LayoutParams(0, dp(38), 1); archiveLp.setMargins(dp(8), 0, 0, 0); actions.addView(removeArchive, archiveLp); card.addView(actions); LinearLayout.LayoutParams lp = new LinearLayout.LayoutParams(-1, -2); lp.setMargins(0, dp(4), 0, 0); card.setLayoutParams(lp); new Thread(() -> { String text = "系统数据 " + formatBytes(LinuxImages.storageBytes(LinuxImages.environment(this, image))) + " · 下载包 " + formatBytes(LinuxImages.storageBytes(LinuxImages.archive(this, image))); runOnUiThread(() -> usage.setText(text)); }).start(); return card; }
     private String formatBytes(long bytes) { if (bytes < 1024 * 1024) return String.format(java.util.Locale.US, "%.1f KB", bytes / 1024.0); if (bytes < 1024L * 1024 * 1024) return String.format(java.util.Locale.US, "%.1f MB", bytes / 1024.0 / 1024.0); return String.format(java.util.Locale.US, "%.2f GB", bytes / 1024.0 / 1024.0 / 1024.0); }
      private void confirmClear(LinuxImages.Image image, TextView usage) { new AlertDialog.Builder(this).setTitle("清理系统数据").setMessage("会清空 " + image.name + " 的已解压系统数据，保留下载包，后续可从下载包重新恢复。").setNegativeButton("取消", null).setPositiveButton("清理", (d, w) -> { new Thread(() -> { boolean ok = deleteTree(LinuxImages.environment(this, image)); runOnUiThread(() -> { usage.setText(ok ? "系统数据已清理 · 下载包仍保留" : "清理未完成"); showPage(); }); }).start(); }).show(); }
      private void confirmClearArchive(LinuxImages.Image image, TextView usage) { new AlertDialog.Builder(this).setTitle("清理下载包").setMessage("会删除 " + image.name + " 的下载压缩包，已安装系统数据会保留。").setNegativeButton("取消", null).setPositiveButton("清理", (d, w) -> { new Thread(() -> { boolean ok = deleteTree(LinuxImages.archive(this, image)); runOnUiThread(() -> { usage.setText(ok ? "下载包已清理 · 系统数据仍保留" : "清理未完成"); showPage(); }); }).start(); }).show(); }
     private Button actionButton(String text, int background, int color) { Button button = new Button(this); button.setText(text); button.setTextSize(12); button.setAllCaps(false); button.setMinWidth(0); button.setMinHeight(0); button.setTextColor(color); button.setBackgroundResource(background); return button; }
    private void confirmRemove(LinuxImages.Image image) { new AlertDialog.Builder(this).setTitle("移除终端环境").setMessage("将删除 " + image.name + " 的全部系统数据和压缩包。").setNegativeButton("取消", null).setPositiveButton("移除", (dialog, which) -> new Thread(() -> { java.io.File environment = LinuxImages.environment(this, image); java.io.File archive = LinuxImages.archive(this, image); boolean removed = removeAsRoot(environment, archive); runOnUiThread(() -> { showPage(); Toast.makeText(this, removed ? "环境已移除，空间已释放" : "移除未完成，请先退出正在运行的终端后重试", Toast.LENGTH_SHORT).show(); }); }).start()).show(); }

    private boolean removeAsRoot(java.io.File root, java.io.File archive) { if (root == null && archive == null) return true; String rootPath = root == null ? "" : root.getAbsolutePath(); String archivePath = archive == null ? "" : archive.getAbsolutePath(); String rootQuoted = "'" + rootPath.replace("'", "'\\''") + "'"; String archiveQuoted = "'" + archivePath.replace("'", "'\\''") + "'"; String command = "for p in " + rootQuoted + "/dev/pts " + rootQuoted + "/dev " + rootQuoted + "/proc " + rootQuoted + "/sys " + rootQuoted + "/tmp " + rootQuoted + "/etc/resolv.conf; do /system/bin/toybox umount -l \"$p\" 2>/dev/null; done; /system/bin/toybox rm -rf " + rootQuoted + " " + archiveQuoted + "; if [ ! -e " + rootQuoted + " ] && [ ! -e " + archiveQuoted + " ]; then exit 0; fi; exit 1"; try { java.lang.Process process = new ProcessBuilder("/system/bin/su", "-c", command).redirectErrorStream(true).start(); return process.waitFor() == 0; } catch (Exception ignored) { return false; } }
    private boolean deleteTree(java.io.File file) { if (file == null || !file.exists()) return true; boolean removed = true; if (file.isDirectory() && !java.nio.file.Files.isSymbolicLink(file.toPath())) { java.io.File[] children = file.listFiles(); if (children != null) for (java.io.File child : children) removed = deleteTree(child) && removed; } try { java.nio.file.Files.deleteIfExists(file.toPath()); } catch (java.io.IOException e) { removed = false; } return removed && !file.exists(); }
}
